version: '3'

services:
    app:
        build: .
        environment:
            - NODE_ENV=${NODE_ENV}
        ports:
            - 3000:3000
        volumes:
            - /app/node_modules
            - .:/app
        command: yarn dev
